name: slideable
description: Flexible and customizable slideable list item for Flutter apps. Add multiple action buttons, control animations, and automatically close open items with ease.
version: 0.0.3
homepage: https://github.com/gikwegbu/flutter_item_slideable
repository: https://github.com/gikwegbu/flutter_item_slideable
issue_tracker: https://github.com/gikwegbu/flutter_item_slideable/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

